# Generated by Django 6.1.1 on 2026-09-24 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('reminder', 'Reminder'), ('final_call', 'Final Call')], max_length=20)),
                ('channel', models.CharField(choices=[('whatsapp_manual', 'WhatsApp Manual (wa.me)'), ('whatsapp_api', 'WhatsApp Meta Cloud API'), ('sms', 'SMS')], default='whatsapp_manual', max_length=30)),
                ('content_sent', models.TextField()),
                ('language', models.CharField(default='English', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='sent', max_length=30)),
                ('external_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='registrants.registrant')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
