# Generated by Django 6.1.1 on 2026-09-24 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(help_text='E.164 format', max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10)),
                ('preferred_language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Tamil', 'Tamil'), ('Bengali', 'Bengali')], default='English', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrants', to='drives.drive')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_donors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('predicted', 'Predicted'), ('attended', 'Attended'), ('no_show', 'No Show')], default='predicted', max_length=20)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('registrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record', to='registrants.registrant')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoutPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_label', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('no_consent', 'No Consent')], default='medium', max_length=20)),
                ('score_value', models.FloatField(default=0.5)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('signals_used', models.JSONField(default=dict)),
                ('registrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turnout_prediction', to='registrants.registrant')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('this_drive', 'This Drive Only'), ('future_drives', 'Future Drives')], max_length=20)),
                ('is_granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='registrants.registrant')),
            ],
            options={
                'unique_together': {('registrant', 'consent_type')},
            },
        ),
    ]
