# Generated by Django 6.1.1 on 2026-09-24 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='registration_status',
            field=models.CharField(default='registered', max_length=30),
        ),
        migrations.AddField(
            model_name='registrant',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='reminder_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrant',
            name='reminder_status',
            field=models.CharField(choices=[('Not Sent', 'Not Sent'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Not Sent', max_length=20),
        ),
        migrations.AddField(
            model_name='registrant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='E.164 format', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='preferred_language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Gujarati', 'Gujarati'), ('Kannada', 'Kannada'), ('Other', 'Other')], default='English', max_length=20),
        ),
    ]
