# Generated by Django 6.1.1 on 2026-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrants', '0002_registrant_registration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='confirmation_status',
            field=models.CharField(default='Sent', max_length=20),
        ),
        migrations.AddField(
            model_name='registrant',
            name='registration_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='registration_status',
            field=models.CharField(default='Registered', max_length=30),
        ),
    ]
