# Generated by Django 6.1.1 on 2026-09-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='actor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='actor_role',
            field=models.CharField(default='System', max_length=50),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='drives.drive'),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
